name: Generate
on:
  push:
    branches:
      - master

jobs:
  generate:
    name: Build
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[data]')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: npm ci
      - name: Generate
        env:
          GEOCODE_API_KEY: ${{ secrets.GEOCODE_API_KEY }}
        run: node ./src/generate.js
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
