name: Release
on:
  push:
    branches:
      - master

jobs:
  data:
    name: Data
    runs-on: ubuntu-latest
    steps:
      - name: Changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: List
        run: |
          echo '${{ steps.file_changes.outputs.files}}'
      - name: Generate
        uses: convictional/trigger-workflow-and-wait@v1.0.1
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          wait_interval: 30
          event_type: generate
          ref: ${{ github.ref }}
        if: ${{ contains(steps.file_changes.outputs.files, 'src/generate.js') }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: data
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Setup
        run: mkdir -p data
      - name: Download
        uses: autovance/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: 'ca-central-1'
          SOURCE_DIR: s3://${{ secrets.AWS_S3_BUCKET }}/data
          DEST_DIR: data
      - name: Unzip
        uses: montudor/action-zip@v0.1.0
        with:
          args: unzip -qq ./data/canadian-city-timezones.zip -d ./src
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_DEPLOY }}
        run: npx semantic-release
